name: simple_html_css
description: This package allows you to use simple HTML and inline CSS styles to style your text in flutter. A fork of css_text package.
version: 3.0.1+1
homepage: https://github.com/ali-thowfeek/simple_html_css_flutter
repository: https://github.com/ali-thowfeek/simple_html_css_flutter
environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter: ">=0.10.3"
  html_unescape: ^2.0.0
  mpcore: ">=0.10.3"
  xml: ^5.0.0
